workflow:
    name: Solar System Pipeline
    rules:
        - if: $CI_COMMIT_BRANCH == 'main' || $CI_COMMIT_BRANCH =~ /^feature/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/ && $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always

stages:
  - test

variables:
  MONGO_URI: 'mongodb+srv://supercluster.4plmtfj.mongodb.net/'
  MONGO_USERNAME: irfu6288_db_user
  MONGO_PASSWORD: $M_DB_PASSWORD

unit_testing:
    stage: test
    image: node:24-alpine
    before_script:
        - npm install
    script:
        - npm test
    